name: "CI"

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  functional-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Temporary large spread, will reduce this soon
        java-version: [8, 11, 17, 21, 24]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}

      - uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/master' }}
          cache-write-only: ${{ github.ref == 'refs/heads/master' }}

      - name: Run functional tests
        run: ./gradlew :artifactregistry-gradle-plugin:functionalTest --info

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [8, 21, 24]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}

      - uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/master' }}
          cache-write-only: ${{ github.ref == 'refs/heads/master' }}

      - name: Run tests
        run: ./gradlew test --info

  publish-for-compatibility-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 24

      - uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/master' }}
          cache-write-only: ${{ github.ref == 'refs/heads/master' }}

      - name: Publish to test Maven repo
        run: ./gradlew publishAllPublicationsToTestMavenRepo --info

      - name: Upload test Maven repo
        uses: actions/upload-artifact@v4
        with:
          name: test-maven-repo
          path: build/testMavenRepo

  compatibility-tests:
    runs-on: ubuntu-latest
    needs: publish-for-compatibility-tests
    strategy:
      fail-fast: false
      matrix:
        java-version: [8, 11, 17, 21, 24]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}

      - name: Set up GCloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/master' }}
          cache-write-only: ${{ github.ref == 'refs/heads/master' }}

      - name: Download test Maven repo
        uses: actions/download-artifact@v4
        with:
          name: test-maven-repo
          path: build/testMavenRepo

      - name: Run compatibility tests
        run: |
          export PATH=$GCLOUD_SDK_PATH/bin:$PATH
          ./tests/run-compatibility-tests.sh rootProjects/basic_gradle_proj --ci-build-id=jdk${{ matrix.java-version }}
